www:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./www/:/usr/share/nginx/html

generator:
  build: .
  dockerfile: ./generator/Dockerfile
  environment:
    - TASK
    - WWW=/usr/share/nginx/html/
  ports:
    - 3000:3000
  volumes:
    - ./generator/src:/src
    - ./style:/style
    - ./content:/content
  volumes_from:
    - www
